name: "Jon Lay"
description: "Designer, developer, founder, culture hacker & noodle aficionado."

author: "Jon Lay"

url: "jonlay.com"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title
highlighter: pygments

# Google Analytics
ga_domain: jonlay.com
ga_tracking_id: UA-51784778-1

gems:
  - jekyll-redirect-from