name: "Jon Lay"
description: "Peopleware, design agencies, and figuring out a path."

author: "Jon Lay"

url: "jonlay.com"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title
pygments: true

# Google Analytics
# ga_domain: m3xm.github.io
# ga_tracking_id: UA-47727049-1
