name: "Jon Lay"
description: "Designer, developer, founder & noodle aficionado."

author: "Jon Lay"

url: "jonlay.com"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title
highlighter: rouge

gems:
  - jekyll-redirect-from
